[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "src/=src/",
  "oz/=lib/openzeppelin-contracts/contracts/",
  "v3-periphery/=lib/v3-periphery/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
