[profile.default]
solc = "0.8.21"
optimizer = true
optimizer_runs = 200

remappings = [
  "src/=src/",
  "forge-std/=lib/forge-std/src/",
  "oz/=lib/openzeppelin-contracts/contracts/",
  "v3-periphery/=lib/v3-periphery/contracts/",
  "@uniswap/v3-core/=lib/v3-core/"
]

[rpc_endpoints]
holesky = "${RPC_URL_HOLESKY}"
sepolia = "${RPC_URL_SEPOLIA}"
mumbai = "${RPC_URL_POLYGON_MUMBAI}"

[etherscan]
holesky = {key = "${ETHERSCAN_KEY}", url = "https://api-holesky.etherscan.io/api"}
sepolia = {key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.etherscan.io/api"}
unreal = {key = "${ETHERSCAN_KEY}", url = "https://unreal.blockscout.com/api"}
mumbai = {key = "${POLYGONSCAN_KEY}", url = "https://api-testnet.polygonscan.com/api"}


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
